### ISSUE TITLE
Move replit React sandbox to a folder in the playground

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/playground#4]
**Context**
- We have a repl, but it would be nice to statically host so we can use as part of CI. (Currently we have to boot up the repl before we use it)
- https://replit.com/@PixieBrixTodd/ReactSandbox

**Comment by fregante** [comment]
If the intention is to use it for CI, I assume you just need a React page/component to be served from a server rather than a full repl with file saving and stuff (which would need its own server or Vercel).

If you want to be able to upload JSX and get a build JS file out I can set up a bundler like Parcel and link its result to GitHub Pages somehow (which normally only publishes static files and Jekyll)

**Comment by twschiller** [comment]
> If the intention is to use it for CI

Sorry, didn't fully flesh out the issue. I want to use it for the Rainforest QA jobs we'll run as part of the extension CI. We'll have the the Rainforest QA test install some blueprints and ensure they work on the page

For the React code in the repl.it, it's totally OK have the playground CI/CD build create a static bundle that it serves up. I'm happy to use whatever build tool is easiest (e.g., Create React App might be easiest since the project doesn't use any special features?)

The only gotcha is the sandbox app currently uses React Router with url path based routing. So that might not be supported by GitHub pages?
